name: RELEASE

on: [workflow_dispatch]

permissions:
  contents: read # for checkout
  
jobs:
  main:
    name: Version and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - uses: nrwl/nx-set-shas@v3
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npx nx run-many -t lint
      # - name: Test
      #   run: npx nx run-many -t test --configuration=ci
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
